# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\darsh\darshapp\changecom.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import updated,error
import qtmodern.styles
import qtmodern.windows


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.mydb = sqlite3.connect('filedb.sqlite')
        self.cur = self.mydb.cursor()
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 170)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.close = QtWidgets.QPushButton(Dialog)
        self.close.setGeometry(QtCore.QRect(600, 110, 93, 28))
        self.close.setObjectName("close")
        self.oldcom = QtWidgets.QLabel(Dialog)
        self.oldcom.setGeometry(QtCore.QRect(30, 20, 150, 25))
        self.oldcom.setObjectName("oldcom")
        self.oldcomw = QtWidgets.QLineEdit(Dialog)
        self.oldcomw.setGeometry(QtCore.QRect(190, 20, 500, 30))
        self.oldcomw.setObjectName("oldcomw")
        self.chngcom = QtWidgets.QLabel(Dialog)
        self.chngcom.setGeometry(QtCore.QRect(30, 60, 150, 25))
        self.chngcom.setObjectName("chngcom")
        self.chngcomw = QtWidgets.QLineEdit(Dialog)
        self.chngcomw.setGeometry(QtCore.QRect(190, 60, 500, 30))
        self.chngcomw.setObjectName("chngcomw")
        self.ok = QtWidgets.QPushButton(Dialog)
        self.ok.setGeometry(QtCore.QRect(500,110, 93, 28))
        self.ok.setObjectName("ok")

        self.retranslateUi(Dialog)
        self.close.clicked.connect(Dialog.close)
        self.ok.clicked.connect(self.clickedOk)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "CHANGE COMPANY"))
        self.close.setText(_translate("Dialog", "Close"))
        self.chngcom.setText(_translate("Dialog", "Change Company"))
        self.ok.setText(_translate("Dialog", "OK"))
        self.oldcom.setText(_translate("Dialog", "Old Company"))


    def clickedOk(self):
        ocom = self.oldcomw.text()
        ncom = self.chngcomw.text()
        self.cur.execute("SELECT * FROM company")
        myres = self.cur.fetchone()
        print(myres)
        self.cur.execute("""UPDATE company SET Nm=? WHERE Nm=?""",(ncom,ocom))
        self.mydb.commit()
        print(self.cur.rowcount)
        if self.cur.rowcount>0:
            self.ud = QtWidgets.QDialog()
            self.ui=updated.Ui_Dialog()
            self.ui.setupUi(self.ud)
            self.ud.show()            
        else:
            self.er = QtWidgets.QDialog()
            self.ui=error.Ui_Dialog()
            self.ui.setupUi(self.er)
            self.er.show()
        
        self.oldcomw.clear()
        self.chngcomw.clear()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    qtmodern.styles.dark(app)
    Dialog = qtmodern.windows.ModernWindow(Dialog)
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
