# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\darsh\darshapp\chngpd.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import updated,error

class Ui_changepd(object):
    def setupUi(self, changepd):
        self.mydb = sqlite3.connect('filedb.sqlite')
        self.cur = self.mydb.cursor()
        changepd.setObjectName("changepd")
        changepd.resize(530, 250)
        font = QtGui.QFont()
        font.setPointSize(10)
        changepd.setFont(font)      
        self.oldpd = QtWidgets.QLabel(changepd)
        self.oldpd.setGeometry(QtCore.QRect(30, 70, 170, 25))
        self.oldpd.setObjectName("oldpd")
        self.username = QtWidgets.QLabel(changepd)
        self.username.setGeometry(QtCore.QRect(30, 30, 170, 25))
        self.username.setObjectName("username")
        self.newpd1 = QtWidgets.QLabel(changepd)
        self.newpd1.setGeometry(QtCore.QRect(30, 110, 170, 25))
        self.newpd1.setObjectName("newpd1")
        self.newpd2 = QtWidgets.QLabel(changepd)
        self.newpd2.setGeometry(QtCore.QRect(30, 150, 170, 25))
        self.newpd2.setObjectName("newpd2")
        self.usernamew = QtWidgets.QLineEdit(changepd)
        self.usernamew.setGeometry(QtCore.QRect(210, 30, 300, 25))
        self.usernamew.setObjectName("usernamew")
        self.oldpdw = QtWidgets.QLineEdit(changepd)
        self.oldpdw.setGeometry(QtCore.QRect(210, 70, 300, 25))
        self.oldpdw.setObjectName("oldpdw")
        self.newpd1w = QtWidgets.QLineEdit(changepd)
        self.newpd1w.setGeometry(QtCore.QRect(210, 110, 300, 25))
        self.newpd1w.setObjectName("newpd1w")
        self.newpd2w = QtWidgets.QLineEdit(changepd)
        self.newpd2w.setGeometry(QtCore.QRect(210, 150, 300, 25))
        self.newpd2w.setObjectName("newpd2w")
        self.ok = QtWidgets.QPushButton(changepd)
        self.ok.setGeometry(QtCore.QRect(330, 200, 90, 30))
        self.ok.setObjectName("ok")
        self.cancel = QtWidgets.QPushButton(changepd)
        self.cancel.setGeometry(QtCore.QRect(430, 200, 90, 30))
        self.cancel.setObjectName("cancel")

        self.retranslateUi(changepd)
        self.cancel.clicked.connect(changepd.close)
        self.ok.clicked.connect(self.clickedOk)
        QtCore.QMetaObject.connectSlotsByName(changepd)


    def clickedOk(self):
        self.opd = self.oldpdw.text()
        self.npd1 =self.newpd1w.text()
        self.npd2 =self.newpd2w.text()
        self.un = self.usernamew.text()
        self.cur.execute("SELECT * FROM users where UserName=? and Password=?",(self.un,self.opd))
        myres = self.cur.fetchone()
        print (myres)
        if myres is None:
            self.er = QtWidgets.QDialog()
            self.ui = error.Ui_Dialog()
            self.ui.setupUi(self.er)
            self.er.show()
            self.oldpdw.clear()
            self.usernamew.clear()
            self.newpd1w.clear()
            self.newpd2w.clear()
        else:
            if self.npd1 == self.npd2:
                self.cur.execute("""UPDATE users  SET Password=? WHERE UserName=?""",(self.npd1,self.un))
                self.mydb.commit()
                if self.cur.rowcount>0 :
                    self.upd = QtWidgets.QDialog()
                    self.ui=updated.Ui_Dialog()
                    self.ui.setupUi(self.upd)
                    self.upd.show()
                else:
                    self.er = QtWidgets.QDialog()
                    self.ui = error.Ui_Dialog()
                    self.ui.setupUi(self.er)
                    self.er.show()
                    self.oldpdw.clear()
                    self.usernamew.clear()
                    self.newpd1w.clear()
                    self.newpd2w.clear()
            else:
                self.er = QtWidgets.QDialog()
                self.ui = error.Ui_Dialog()
                self.ui.setupUi(self.er)
                self.er.show()
                self.oldpdw.clear()
                self.usernamew.clear()
                self.newpd1w.clear()
                self.newpd2w.clear()                
            print(self.cur.rowcount)
                
                
    def retranslateUi(self, changepd):
        _translate = QtCore.QCoreApplication.translate
        changepd.setWindowTitle(_translate("changepd", "CHANGE PASSWORD"))
        self.ok.setText(_translate("changepd", "OK"))
        self.cancel.setText(_translate("changepd", "Cancel"))
        self.oldpd.setText(_translate("changepd", "Old Password"))
        self.newpd1.setText(_translate("changepd", "New Password"))
        self.newpd2.setText(_translate("changepd", "Retype New Password"))
        self.username.setText(_translate("changepd", "Username"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    changepd = QtWidgets.QDialog()
    ui = Ui_changepd()
    ui.setupUi(changepd)
    changepd.show()
    sys.exit(app.exec_())
