# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\darsh\darshapp\dbbms.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import changecom,chngpd,compmstr,invoice,partymstr,productmstr,salesregister,nochng,updated
from PyQt5 import QtCore, QtGui, QtWidgets
import qtmodern.styles
import qtmodern.windows


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 37))
        self.menubar.setObjectName("menubar")
        self.menuMASTER = QtWidgets.QMenu(self.menubar)
        self.menuMASTER.setObjectName("menuMASTER")
        self.menuINVOICE = QtWidgets.QMenu(self.menubar)
        self.menuINVOICE.setObjectName("menuINVOICE")
        self.menuREPORT = QtWidgets.QMenu(self.menubar)
        self.menuREPORT.setObjectName("menuREPORT")
        self.menuADMINISTRATION = QtWidgets.QMenu(self.menubar)
        self.menuADMINISTRATION.setObjectName("menuADMINISTRATION")
        self.menuEXIT = QtWidgets.QMenu(self.menubar)
        self.menuEXIT.setObjectName("menuEXIT")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCOMPANY_MASTER = QtWidgets.QAction(MainWindow)
        self.actionCOMPANY_MASTER.setObjectName("actionCOMPANY_MASTER")
        self.actionPRODUCT_MASTER = QtWidgets.QAction(MainWindow)
        self.actionPRODUCT_MASTER.setObjectName("actionPRODUCT_MASTER")
        self.actionPARTY_MASTER = QtWidgets.QAction(MainWindow)
        self.actionPARTY_MASTER.setObjectName("actionPARTY_MASTER")
        self.actionSALE_MASTER = QtWidgets.QAction(MainWindow)
        self.actionSALE_MASTER.setObjectName("actionSALE_MASTER")
        self.actionCHANGE_COMPANY = QtWidgets.QAction(MainWindow)
        self.actionCHANGE_COMPANY.setObjectName("actionCHANGE_COMPANY")
        self.actionCHANGE_PASSWORD = QtWidgets.QAction(MainWindow)
        self.actionCHANGE_PASSWORD.setObjectName("actionCHANGE_PASSWORD")
        self.actionBILL_INVOICE = QtWidgets.QAction(MainWindow)
        self.actionBILL_INVOICE.setObjectName("actionBILL_INVOICE")
        self.actionQUIT = QtWidgets.QAction(MainWindow)
        self.actionQUIT.setObjectName("actionQUIT")
        self.menuMASTER.addAction(self.actionCOMPANY_MASTER)
        self.menuMASTER.addAction(self.actionPRODUCT_MASTER)
        self.menuMASTER.addAction(self.actionPARTY_MASTER)
        self.menuINVOICE.addAction(self.actionBILL_INVOICE)
        self.menuREPORT.addAction(self.actionSALE_MASTER)
        self.menuADMINISTRATION.addAction(self.actionCHANGE_COMPANY)
        self.menuADMINISTRATION.addAction(self.actionCHANGE_PASSWORD)
        self.menuEXIT.addAction(self.actionQUIT)
        self.menubar.addAction(self.menuMASTER.menuAction())
        self.menubar.addAction(self.menuINVOICE.menuAction())
        self.menubar.addAction(self.menuREPORT.menuAction())
        self.menubar.addAction(self.menuADMINISTRATION.menuAction())
        self.menubar.addAction(self.menuEXIT.menuAction())

        self.retranslateUi(MainWindow)
        self.actionQUIT.triggered.connect(MainWindow.close)
        self.actionCOMPANY_MASTER.triggered.connect(self.openCompMaster)
        self.actionPRODUCT_MASTER.triggered.connect(self.openProdMaster)
        self.actionPARTY_MASTER.triggered.connect(self.openPartyMaster)
        self.actionSALE_MASTER.triggered.connect(self.openSaleRegister)
        self.actionCHANGE_COMPANY.triggered.connect(self.openChngComp)
        self.actionCHANGE_PASSWORD.triggered.connect(self.openChngPd)
        self.actionBILL_INVOICE.triggered.connect(self.openBillInvoice)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuMASTER.setTitle(_translate("MainWindow", "MASTER"))
        self.menuINVOICE.setTitle(_translate("MainWindow", "INVOICE"))
        self.menuREPORT.setTitle(_translate("MainWindow", "REPORT"))
        self.menuADMINISTRATION.setTitle(_translate("MainWindow", "ADMINISTRATION "))
        self.menuEXIT.setTitle(_translate("MainWindow", "EXIT"))
        self.actionCOMPANY_MASTER.setText(_translate("MainWindow", "COMPANY MASTER"))
        self.actionPRODUCT_MASTER.setText(_translate("MainWindow", "PRODUCT MASTER"))
        self.actionPARTY_MASTER.setText(_translate("MainWindow", "PARTY MASTER"))
        self.actionSALE_MASTER.setText(_translate("MainWindow", "SALE REGISTER"))
        self.actionCHANGE_COMPANY.setText(_translate("MainWindow", "CHANGE COMPANY"))
        self.actionCHANGE_PASSWORD.setText(_translate("MainWindow", "CHANGE PASSWORD"))
        self.actionBILL_INVOICE.setText(_translate("MainWindow", "BILL INVOICE"))
        self.actionQUIT.setText(_translate("MainWindow", "QUIT"))

    def openCompMaster(self):
        self.cm = QtWidgets.QDialog()
        self.ui=compmstr.Ui_Dialog()
        self.ui.setupUi(self.cm)
        self.cm.show()
    def openProdMaster(self):
        self.pm=QtWidgets.QDialog()
        self.ui=productmstr.Ui_productmaster()
        self.ui.setupUi(self.pm)
        self.pm.show()
    def openPartyMaster(self):
        self.pa = QtWidgets.QDialog()
        self.ui=partymstr.Ui_Dialog()
        self.ui.setupUi(self.pa)
        self.pa.show()
    def openBillInvoice(self):
        self.bi = QtWidgets.QDialog()
        self.ui=invoice.Ui_inv()
        self.ui.setupUi(self.bi)
        self.bi.show()
    def openSaleRegister(self):
        self.sr = QtWidgets.QDialog()
        self.ui=salesregister.Ui_Dialog()
        self.ui.setupUi(self.sr)
        self.sr.show()
    def openChngComp(self):
        self.cc= QtWidgets.QDialog()
        self.ui=changecom.Ui_Dialog()
        self.ui.setupUi(self.cc)
        self.cc.show()
    def openChngPd(self):
        self.cp = QtWidgets.QDialog()
        self.ui=chngpd.Ui_changepd()
        self.ui.setupUi(self.cp)
        self.cp.show()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    qtmodern.styles.dark(app)
    MainWindow = qtmodern.windows.ModernWindow(MainWindow)
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
