# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\darsh\darshapp\nochng.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 130)
        font = QtGui.QFont()
        font.setPointSize(15)
        Dialog.setFont(font)
        self.nochng = QtWidgets.QLabel(Dialog)
        self.nochng.setGeometry(QtCore.QRect(0, 0, 300, 80))
        self.nochng.setObjectName("nochng")
        self.ok = QtWidgets.QPushButton(Dialog)
        self.ok.setCheckable(True)
        self.ok.setGeometry(QtCore.QRect(100,80,100,40))
        self.ok.setObjectName("ok")        
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.ok.clicked.connect(Dialog.close)       
      
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "NOTE"))
        self.nochng.setText(_translate("Dialog", "      No changes made !"))
        self.ok.setText (_translate("Dialog","OK"))
        
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
