# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'salesregister.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets,QtPrintSupport
from PyQt5.QtCore import QDate
import sqlite3
from PyQt5.QtSql import *
import norecord
import qtmodern.styles
import qtmodern.windows

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.mydb = sqlite3.connect('filedb.sqlite')
        self.cur= self.mydb.cursor()
        Dialog.setObjectName("Dialog")
        Dialog.resize(1800, 850)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.show = QtWidgets.QPushButton(Dialog)
        self.show.setGeometry(QtCore.QRect(30, 770, 120, 50))
        self.show.setObjectName("show")
        self.close = QtWidgets.QPushButton(Dialog)
        self.close.setGeometry(QtCore.QRect(1650, 770, 120, 50))
        self.close.setObjectName("close")
        self.printw = QtWidgets.QPushButton(Dialog)
        self.printw.setGeometry(QtCore.QRect(180, 770, 120, 50))
        self.printw.setObjectName("printw")
        self.start = QtWidgets.QLabel(Dialog)
        self.start.setGeometry(QtCore.QRect(40, 30, 100, 25))
        self.start.setObjectName("start")
        self.startw = QtWidgets.QDateEdit(Dialog)
        self.startw.setGeometry(QtCore.QRect(150, 30, 110, 25))
        self.startw.setObjectName("startw")
        self.startw.setDate(QDate.currentDate())
        self.end = QtWidgets.QLabel(Dialog)
        self.end.setGeometry(QtCore.QRect(540, 30, 100, 25))
        self.end.setObjectName("end")
        self.endw = QtWidgets.QDateEdit(Dialog)
        self.endw.setGeometry(QtCore.QRect(650, 30, 110, 25))
        self.endw.setObjectName("endw")
        self.pprev = QtWidgets.QPushButton(Dialog)
        self.pprev.setGeometry(QtCore.QRect(1450, 770, 180, 50))
        self.pprev.setObjectName("pprev")
        self.endw.setDate(QDate.currentDate())
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 1780, 680))
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setObjectName("tableWidget")
        header = self.tableWidget.horizontalHeader()       
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(5, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(6, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(7, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(8, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(9, QtWidgets.QHeaderView.ResizeToContents)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 9, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)

        self.retranslateUi(Dialog)
        self.close.clicked.connect(Dialog.close)
        self.show.clicked.connect(self.whenShowed)
        self.printw.clicked.connect(self.handlePrint)
        self.pprev.clicked.connect(self.handlePreview)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def handlePrint(self):
        dialog = QtPrintSupport.QPrintDialog()
        if dialog.exec_() == QtWidgets.QDialog.Accepted:
            self.handlePaintRequest(dialog.printer())

    def handlePreview(self):
        dialog = QtPrintSupport.QPrintPreviewDialog()
        dialog.paintRequested.connect(self.handlePaintRequest)
        dialog.exec_()

    def handlePaintRequest(self, printer):
        document = QtGui.QTextDocument()
        cursor = QtGui.QTextCursor(document)
        tb = cursor.insertTable(
            self.tableWidget.rowCount(), self.tableWidget.columnCount())
        for row in range(tb.rows()):
            for col in range(tb.columns()):
                thing =self.tableWidget.item(row, col)
                if thing is None :
                    cursor.insertText("                  ")
                else:
                    cursor.insertText(self.tableWidget.item(row, col).text()) 
                cursor.movePosition(QtGui.QTextCursor.NextCell)
        document.print_(printer)


    def whenShowed(self):
        startdate = self.startw.date().toPyDate()
        enddate = self.endw.date().toPyDate()
        self.cur.execute("""SELECT
         BillNo,
         dDt,
         PNm,
         GSTNo,
         Total,
         TotCGST,
         TotSGST,
         TotIGST,
         ExpAmt2,
         GTot FROM Bill_Master
         WHERE dDt BETWEEN ? AND ?""",(startdate,enddate))
        a = self.cur.fetchall()
        b = []
        if a == b :
            self.nr = QtWidgets.QDialog()
            self.ui=norecord.Ui_Dialog()
            self.ui.setupUi(self.nr)
            self.nr.show()
        else :
            self.tableWidget.setRowCount(0)
            row_number=0
            for row_number, row_data in enumerate(a):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,column_number,QtWidgets.QTableWidgetItem(str(data)))
            self.tableWidget.insertRow(row_number + 1)
            self.tableWidget.insertRow(row_number + 2)
            c = row_number + 2
            self.tableWidget.setItem(c,2,QtWidgets.QTableWidgetItem("TOTAL"))
            self.cur.execute("""SELECT SUM(Total) AS sum FROM Bill_Master WHERE dDt BETWEEN ? AND ?""",(startdate,enddate))
            result = self.cur.fetchall()
            for i in result:
                x = i[0]
                y = "{:.2f}".format(x)
            self.tableWidget.setItem(c,4,QtWidgets.QTableWidgetItem(str(y)))
            self.cur.execute("""SELECT SUM(TotCGST) AS sum FROM Bill_Master WHERE dDt BETWEEN ? AND ?""",(startdate,enddate))
            result = self.cur.fetchall()
            for i in result:
                x = i[0]
                y = "{:.2f}".format(x)
            self.tableWidget.setItem(c,5,QtWidgets.QTableWidgetItem(str(y)))
            self.cur.execute("""SELECT SUM(TotSGST) AS sum FROM Bill_Master WHERE dDt BETWEEN ? AND ?""",(startdate,enddate))
            result = self.cur.fetchall()
            for i in result:
                x = i[0]
                y = "{:.2f}".format(x)
            self.tableWidget.setItem(c,6,QtWidgets.QTableWidgetItem(str(y)))
            self.cur.execute("""SELECT SUM(TotIGST) AS sum FROM Bill_Master WHERE dDt BETWEEN ? AND ?""",(startdate,enddate))
            result = self.cur.fetchall()
            for i in result:
                x = i[0]
                y = "{:.2f}".format(x)
            self.tableWidget.setItem(c,7,QtWidgets.QTableWidgetItem(str(y)))
            self.cur.execute("""SELECT SUM(ExpAmt2) AS sum FROM Bill_Master WHERE dDt BETWEEN ? AND ?""",(startdate,enddate))
            result = self.cur.fetchall()
            for i in result:
                x = i[0]
                y = "{:.2f}".format(x)
            self.tableWidget.setItem(c,8,QtWidgets.QTableWidgetItem(str(y)))
            self.cur.execute("""SELECT SUM(GTot) AS sum FROM Bill_Master WHERE dDt BETWEEN ? AND ?""",(startdate,enddate))
            result = self.cur.fetchall()
            for i in result:
                x = i[0]
                y = "{:.2f}".format(x)
            self.tableWidget.setItem(c,9,QtWidgets.QTableWidgetItem(str(y)))


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.close.setText(_translate("Dialog", "Close"))
        self.show.setText(_translate("Dialog", "Show"))
        self.printw.setText(_translate("Dialog", "Print"))
        self.start.setText(_translate("Dialog", "Start Date"))
        self.end.setText(_translate("Dialog", "End Date"))
        self.pprev.setText(_translate("Dialog", "Print Preview"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Bill No."))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Date"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Party"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "GSTIN"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Taxable Value"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "CGST"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "SGST"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "IGST"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Exp / RoundOff"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "Grand Total"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled) 


if __name__ == "__main__":
    import sys 
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    qtmodern.styles.dark(app)
    Dialog = qtmodern.windows.ModernWindow(Dialog)
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

